# Generated by Django 4.0 on 2022-01-15 08:06

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=30, region=None, verbose_name='phone number')),
                ('about_me', models.TextField(default='Say something about yourself', verbose_name='about me')),
                ('liscence', models.TextField(blank=True, max_length=20, null=True, verbose_name='Real Estate Liscence')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='profile photo')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='INA', max_length=2, verbose_name='country')),
                ('city', models.CharField(default='Jakarta', max_length=180, verbose_name='city')),
                ('is_seller', models.BooleanField(default=False, help_text='Are You looking to buy property', verbose_name='Seller')),
                ('is_buyer', models.BooleanField(default=False, help_text='Are You looking to sell property', verbose_name='Buyer')),
                ('is_agent', models.BooleanField(default=False, help_text='Are You agent property?', verbose_name='Agent')),
                ('top_agent', models.BooleanField(default=False, verbose_name='top agent')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
