# Generated by Django 4.0 on 2022-01-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_reviews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='numbers of reviews'),
        ),
    ]
