# Generated by Django 4.0 on 2022-01-25 16:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='IDN', max_length=2, verbose_name='Country'),
        ),
    ]
