version: "3"

services:
    api:
        container_name: estate-api-container
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - postgres-db
        

    postgres-db:
        container_name: estate-db-postgres12
        image: postgres:12.0-alpine
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        
volumes:
   
    static_volume:
    media_volume:
    postgres_data:


