# Generated by Django 4.0 on 2022-02-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='plot_ara',
            new_name='plot_area',
        ),
    ]
