# Generated by Django 4.0 on 2022-02-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='update_at',
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
