# Generated by Django 4.0 on 2022-02-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rename_craeted_at_rating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
