# Generated by Django 4.0 on 2022-02-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_rating_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='argument',
            new_name='comment',
        ),
    ]
